Controllers/DepartmentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using StudentsEnrollment.Data;
using StudentsEnrollment.Data.Entities;
using StudentsEnrollment.Models;

namespace StudentsEnrollment.Controllers
{
    [Authorize]
    public class DepartmentController : Controller
    {
        private readonly ApplicationDbContext _application;

        public DepartmentController(ApplicationDbContext a)
        {
            _application = a;
        }
        public ActionResult Index()
        {
            var model = _application.Departments.Select(dp => new DepModel
            {
                Name = dp.DepartmentName,
                Count = dp.StudentCount,
                ID = dp.Id
            }).ToList();


            return View(model);
        }

        public IActionResult Delete(int id)
        {
            
            List<string> list = new List<string>();

            foreach(Department d in _application.Departments)
            {
                if (d.Id == id)
                    continue;
                list.Add(d.DepartmentName);
            }

            DepListModel model = new DepListModel
            {
                DeletedDep = new DepModel { ID = id },
                ExistingDepsNames = list
            };

            return View(model);
        }

        [HttpPost]
        public IActionResult Delete(DepListModel model, string deletionOption)
        {
            var dep = _application.Departments.FirstOrDefault(d => d.Id == model.DeletedDep.ID);
            model.DeletedDep.Name = dep.DepartmentName;

            if(deletionOption == "relocate")
            {
                
                foreach (Student student in _application.Students)
                {
                    if (student.Department.DepartmentName == model.DeletedDep.Name)
                    {
                        //return Json(new { isValueValid = deletionOption });
                        var d = _application.Departments
                                            .FirstOrDefault(item => item.DepartmentName == model.ChangedDepName);
                        student.Department = d;
                        _application.Entry(student).State = EntityState.Modified;
                    }
                        
                }
            }

            _application.Departments.Remove(dep);
            _application.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Add()
        {
            DepModel model = new DepModel();

            return View(model);
        }

        [HttpPost]

        public IActionResult Add(DepModel model)
        {
            if (ModelState.IsValid)
            {
                foreach(Department d in _application.Departments)
                {
                    if (d.DepartmentName == model.Name)
                        return RedirectToAction("Index");
                }
                Department dep = new Department
                {
                    DepartmentName = model.Name,
                };

                _application.Departments.Add(dep);
                _application.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }


        // GET: DepartmentController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: DepartmentController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/StudentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;
using StudentsEnrollment.Data;
using StudentsEnrollment.Data.Entities;
using StudentsEnrollment.Models;


namespace StudentsEnrollment.Controllers
{
    [Authorize]
    public class StudentController : Controller
    {
        private readonly ApplicationDbContext _application;

        public StudentController(ApplicationDbContext a)
        {
            _application = a;
        }
        public IActionResult Index()
        {
            var students = _application.Students.Select(student => new StudentModel
            {
                ID = student.Id,
                Name = student.StudentName,
                Surname = student.StudentSurname,
                Age = student.Age,
                Department = student.Department.ToString()

            }).ToList();

            return View(students);
        }

        public IActionResult Add()
        {
            DepNameListAndStudentModel model;
            
            List<string> departments = new List<string>();
            foreach(Department d in _application.Departments)
            {
                departments.Add(d.DepartmentName);
            }
            model = new DepNameListAndStudentModel()
            {
                student = new StudentModel(),
                departmnetsNames = departments
            };

            
            return View(model);
        }

        [HttpPost]

        public IActionResult Add(DepNameListAndStudentModel model)
        {
            
            if (ModelState.IsValid)
            {
                Student student = new Student
                {
                    StudentName = model.student.Name,
                    StudentSurname = model.student.Surname,
                    Age = model.student.Age,
                };

                foreach (Department item in _application.Departments)
                {
                    if (item.DepartmentName == model.student.Department)
                    {
                        student.Department = item;
                        break;
                    }

                }

                _application.Students.AddAsync(student);
                _application.SaveChanges();
                return RedirectToAction("Index");
            }

            return View();
            
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            DepNameListAndStudentModel model;

            var student = _application.Students.Include(s => s.Department).FirstOrDefault(b => b.Id == id);

            if (student == null)
            {

                return NotFound(); 
            }

            StudentModel s = new StudentModel
            {
                Name = student.StudentName,
                Age = student.Age,
                Surname = student.StudentSurname,
                ID = student.Id,
                Department = student.Department.ToString()
            };

            List<string> l = new List<string>();
            foreach (Department d in _application.Departments)
                l.Add(d.DepartmentName);

            model = new DepNameListAndStudentModel
            {
                student = s,
                departmnetsNames = l
            };
            

            return View(model);
        }

        // POST: StudentController/Edit/5
        [HttpPost]
        
        public ActionResult Edit(DepNameListAndStudentModel model)
        {
            StudentModel st = model.student;

            var student = _application.Students.FirstOrDefault(s => s.Id == st.ID);


            if (student != null)
            {
                student.StudentName = st.Name;
                student.StudentSurname = st.Surname;
                student.Age = st.Age;
            }

            
            foreach (Department item in _application.Departments)
            {
               
                if (item.DepartmentName == st.Department)
                {
                    
                    student.Department = item;
                    
                    break;
                }
            }

            _application.Entry(student).State = EntityState.Modified;
            _application.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            
            try
            {
      
                var student = _application.Students.Include(s=> s.Department)
                                                   .FirstOrDefault(b => b.Id == id);
                if (student != null)
                {
                    _application.Students.Remove(student);
                    _application.SaveChanges();
                    
                    return Json(new { success = true });
                }
                return Json(new { success = false, message = "Student not found" });
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.Message });
            }

        }

     }
}

Views/Department/Add.cshtml
@{
    ViewBag.Title = "Add Department";
}


@model DepModel

@using (Html.BeginForm())
{
    <body>
        <h1>Add Department</h1>
        <!-- Name -->
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            <input type="submit" value="Add Department" class="btn btn-primary" />
        </div>
    </body>
}

Views/Department/Delete.cshtml
@{
    ViewBag.Title = "Delete";
}

@model DepListModel


<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Your Page Title</title>

    <style>
        /* CSS styles go here */
        body {
            font-family: Arial, sans-serif;
            background-color: #f0f0f0;
            margin: 0;
            padding: 0;
        }

        header {
            background-color: #333;
            color: #fff;
            padding: 10px;
            text-align: center;
        }

        .container {
            max-width: 800px;
            margin: 20px auto;
            background-color: #fff;
            padding: 20px;
            border: 1px solid #ccc;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        h1, h2, h3 {
            color: #333;
        }

        p {
            line-height: 1.6;
        }

        a {
            color: #007bff;
            text-decoration: none;
        }

            a:hover {
                text-decoration: underline;
            }
    </style>
</head>


<body>
    @using (Html.BeginForm())
    {
        <form method="post" action="@Url.Action("DeleteDepartment", "DepartmentController")">

            <p>Choose an option:</p>
            <label>
                <input type="radio" name="deletionOption" value="deleteAll" checked onchange="disableDropdown()" /> Delete all students
            </label>
            <br />
            <label>
                <input type="radio" name="deletionOption" value="relocate" onchange="enableDropdown()" /> Relocate students to:

                <div class="form-group">
                    @Html.LabelFor(model => model.ChangedDepName, htmlAttributes: new { @class = "control-label" })
                    @Html.DropDownListFor(model => model.ChangedDepName, new SelectList(Model.ExistingDepsNames), new { @class = "form-control", id = "ddlDepName", disabled = "disabled" })
                    @Html.ValidationMessageFor(model => model.ChangedDepName, "", new { @class = "text-danger" })
                </div>
            </label>

            @Html.HiddenFor(model => model.DeletedDep.ID)

            <div>
                <button type="submit">Delete Department</button>
                <button type="submit" asp-controller="Department" asp-action="Index">Cancel</button>
            </div>
        </form>
    }

    <script>
        function enableDropdown() {
            document.getElementById("ddlDepName").removeAttribute("disabled");
        }

        function disableDropdown() {
            document.getElementById("ddlDepName").setAttribute("disabled", "disabled");
        }
    </script>
</body>
</html>

Views/Department/Index.cshtml
@{
    Layout = "_DepLayout";
}
@{
    ViewData["Title"] = "Departaments";
}

@model IEnumerable<DepModel>

<!DOCTYPE html>
<html>
<head>
    <style>
        /* Define CSS styles for the table */
        table {
            border-collapse: collapse;
            width: 100%;
        }

        th, td {
            border: 1px solid #ddd;
            text-align: left;
            padding: 8px;
        }

        tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        th {
            
            color: black;
        }
    </style>
</head>
<body>
    <h1>Department Information</h1>
    <table>
        <tr>
            <th>Name</th>
            <th>Count</th>
            <th>Delete</th>
            <th>Edit</th>
        </tr>
        <tbody>
            @foreach (var item in Model)
            {
                <tr data-dep-id="@item.ID">
                    
                    <td>@item.Name</td>
                    <td>@item.Count</td>
                    <td><a asp-action="Delete" asp-controller="Department" asp-route-id="@item.ID">Delete</a></td>
                    <td><a asp-action="Edit" asp-controller="Student" asp-route-id="@item.ID">Edit</a></td>
                </tr>
            }
        </tbody>
        
    </table>
</body>
</html>